In [6]:
# NUMPY is stand for the NUMERICAL PYTHON .
# NUMPY is a libirary of python which helps the Large amount of data very quickly.
# USIng ARRAY.

33.82


In [10]:
# EXAMPLE FOR NUMPY
import numpy as np

tempr = np.array([32.5, 31.8, 33.0, 35.2, 36.6])
avg=np.mean(tempr)
print(avg)

33.82


In [12]:
# FEATURES OF NUMPY :
# (1) : SPEED = NUMPY is 50-100 times faster then the normal Python List.
# (2) : LESS MEMORY = It use less RAM (because of it data will run smoothly )
# (3) : EASY MATH OPERATION = Easy for any calCulation.
# (4) : USED IN AI, DATA SCIENCE ,DATA ANALYSIS etc = Most important, everything is depending on the NUMPY.
# ITS A TURBO CHARGE CALCULATOR

In [14]:
# USE OF NUMPY IN DIFFERNT SECTORS :
# 1. DATA SCIENCE.
# 2. ML AND AI. 
# 3. STOCK MARKET AND FINENCE.
# 4. MEDICAL RESEARCH.
# 5. IMAGE PROCESSING.

In [16]:
# DIFFERENCE BETWEEN NUMPY AND PYTHON LIST:
#           PYTHON LIST                         NUMPY
# (SPEED)     SLOW                               FAST 50-100 TIMES
# (MEMORY)   USE MORE MEMORY                     USE LESS MEMORY
# (CALCU.)   NEED LOOPS (good with small data)   EASY CALCULATION. (good with big data)


In [20]:
# how to install NUMPY (pip install numpy ) STEP 1.

import numpy as np    # import numpy to make it functional STEP 2.

In [24]:
 # EXAMPLE :
python_list=[1,2,3,4,5]
print(python_list)


import numpy as np
numpy_array=np.array([1,2,3,4,5])
print(numpy_array)   # numpy array come without coma because its stores very eficintly

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [26]:
# WHAT IS ARRAY : COLLECTION OF NUMBERS OR COLLECTION OF VALUE WHICH STORES TOGETHER IN AN ORGNISED WAY.
# ARRAY ALLOWS US TO DO ANY MATHMETICAL CALCULATION QUICKLY.
# EXAMPLE USING ARRAY :
marks =[90,91,92,85,76]   # storing all values in one varaible insted of making differnt variable for all values


In [28]:
# 1. 0-dimensional array ( O-D ARRAYS ) : These array hold single values.
# 2. 1-D array : These are linear arrays, similar to a list, with elements arranged in a single row.
# 3. 2-D Arrays (Matrices): These arrays are structured in rows and columns, forming a rectangular grid.
# 4. 3-D Arrays / Multi-D (Tensors): These arrays can be thought of as a collection of 2-D arrays or matrices.
# 5. N-D Arrays: NumPy supports arrays with an arbitrary number of dimensions, referred to as ndarrays.

In [32]:
#  1-D array : a list of numbers which present in a ROW

ar_1d = np.array([10,20,30,40,50])

print(ar_1d)

[10 20 30 40 50]


In [44]:
# 2-D Arrays : its has ROWS and COLOUMS 
# data present in ROW AND COLOUM

arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
        

print(arr_2d)  # data present in a grid


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
# 3-D Arrays / Multi-D (Tensors) : it hase more then 2-d array.
# it has multiple layes of storage data.


# MATRIX : its a 2-D array in which numbers stores in ROW and COLOUM

matrix = np.array([[2,4,6],[8,10,12]])

print(matrix)





[[ 2  4  6]
 [ 8 10 12]]


In [51]:
# CREATING ARRAY FROM PYTHON LIST :
# Numpy gives a ARRAY function that convert the PYTHON LIST into NUMPY ARRAY.

# SYNTAX :

arr=np.array([1,2,3,4]) # list converting into array
print(arr)        # it will use when you already have a list and we want to convert the list into numpy array.

[1 2 3 4]


In [53]:
# CREATING ARRAY WITH DEFULT VALUES :
# NUMPY HAS A BUILT IN FUNCTION > WHICH IS ZEROS FUNCTION

# SYNTAX : NP.ZEROS(SHAPE)

zeros_array=np.zeros(3)
print(zeros_array)

[0. 0. 0.]


In [58]:
# CREATING ARRAY BYB ONSE FUNCTION :
# ones(shape)

ones_array = np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [62]:
# FULL FUNCTION : in case you dont want to full the array by zero or onse.
# full(shape,value)

filled_array = np.full((2,2),7)  # (shape = 2,2)  (value = 7)
print(filled_array)

[[7 7]
 [7 7]]


In [64]:
# CREATING SEQUENCES OF NUMBER IN NUMPY :
# arange ()     ## arange function.
# SYNTAX : 
# arang(start,stop,step)
arr = np.arange(1,10,2)
print(arr)   # RETURNIG NUMPY ARRAY

[1 3 5 7 9]


In [66]:
# CREATING IDENTITY MATRICS : is a square matrix with onces on the digaonal and zeros else where.
# eye(size)

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [68]:
# example

identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
