In [2]:
# NUMPY BASIC 1 :

In [4]:
# What is NumPy ?

# NumPy is a Python library used for working with arrays.
# It also has functions for working in domain of linear algebra, fourier transform, and matrices.
# NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
# NumPy stands for Numerical Python.

In [6]:
# Why Use NumPy ?

# In Python we have lists that serve the purpose of arrays, but they are slow to process.
# NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
# The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
# Arrays are very frequently used in data science, where speed and resources are very important.

In [20]:
# Why is NumPy Faster Than Lists?

# NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
# This behavior is called locality of reference in computer science.
# This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

In [22]:
# Which Language is NumPy written in?
# NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

In [12]:
# Import NumPy .
# Once NumPy is installed, import it in your applications by adding the import keyword:
# import numpy 

In [14]:
# EXAMPLE : 
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [16]:
# NumPy as np :
# NumPy is usually imported under the np alias .
# alias: In Python alias are an alternate name for referring to the same thing.
# Create an alias with the as keyword while importing:
# import numpy as np

In [18]:
# EXAMPLE : Now the NumPy package can be referred to as np instead of numpy.


import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [26]:
# Checking NumPy Version
 #The version string is stored under __version__ attribute.

# Example
import numpy as np

print(np.__version__)

1.26.4


In [28]:
# Create a NumPy ndarray Object :

# NumPy is used to work with arrays. The array object in NumPy is called ndarray.
# We can create a NumPy ndarray object by using the array() function.

# Example :
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [30]:
# type(): This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is numpy.ndarray type.
# To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [32]:
# Example :
# Use a tuple to create a NumPy array:

import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [34]:
# NumPy Array Slicing :
# Slicing arrays :>
# Slicing in python means taking elements from one given index to another given index.

# We pass slice instead of index like this: [start:end].
# We can also define the step, like this: [start:end:step].
# If we don't pass start its considered 0
# If we don't pass end its considered length of array in that dimension
# If we don't pass step its considered 1

In [38]:
# Example :
# Slice elements from index 1 to index 5 from the following array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])



[2 3 4 5]


In [40]:
# Note: The result includes the start index, but excludes the end index.
# Example :
# Slice elements from index 4 to the end of the array:


import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])


[5 6 7]


In [42]:
# Example
# Slice elements from the beginning to index 4 (not included):

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [44]:
# Negative Slicing :
# Use the minus operator to refer to an index from the end:

# Example :
# Slice from the index 3 from the end to index 1 from the end:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [46]:
# STEP :
# Use the step value to determine the step of the slicing :

# Example :
# Return every other element from index 1 to index 5 :

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [48]:
# Example :
# Return every other element from the entire array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [50]:
# NumPy Data Types :

# Data Types in Python...>
# By default Python have these data types:

# strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
# integer - used to represent integer numbers. e.g. -1, -2, -3
# float - used to represent real numbers. e.g. 1.2, 42.42
# boolean - used to represent True or False.
# complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

In [52]:
# Data Types in NumPy :
# NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

# Below is a list of all data types in NumPy and the characters used to represent them....>

# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

In [54]:
# Checking the Data Type of an Array
# The NumPy array object has a property called dtype that returns the data type of the array:

# Example :
# Get the data type of an array object:

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [56]:
# Example
# Get the data type of an array containing strings:

import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [58]:
# Creating Arrays With a Defined Data Type
# We use the array() function to create arrays, this function can take an optional argument:
# dtype that allows us to define the expected data type of the array elements:

In [60]:
# Example
# Create an array with data type string:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [62]:
# Example
# Create an array with data type 4 bytes integer:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [70]:
# Converting Data Type on Existing Arrays :

# The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.
# The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
# The data type can be specified using a string, like 'f' for float, 'i' for integer etc. 
# or you can use the data type directly like float for float and int for integer.

In [72]:
# Example :
# Change data type from float to integer by using 'i' as parameter value:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [74]:
# Example :
# Change data type from float to integer by using int as parameter value:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [76]:
# Example :
# Change data type from integer to boolean:

import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool
